name: update-production         # the name of the workflow
on:                             # the event on which to execute the workflow
  push:
    branches:
      - master
jobs:                           # jobs to execute on event
  
  install-ssh:
    runs-on: ubuntu-latest      # the type of runner this will execute on
    steps:
      - run: apt install -y openssh-client
  
  add-private-key-to-runner:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.ssh
      - run: echo '${{ SSH_PRIVATE_KEY }}' >> ~/.ssh/approved_keys
  
  ssh-into-production-server:
    runs-on: ubuntu-latest
    steps:
      - run: ssh ${{ PRODUCTION_USER }}@${{ PRODUCTION_SERVER }}
      - run: ls -la