name: update-production         # the name of the workflow
on:                             # the event on which to execute the workflow
  push:
    branches:
      - master
jobs:                           # jobs to execute on event
  
  ssh-to-prod-server:
    runs-on: ubuntu-latest      # the type of runner this will execute on
    steps:
      - name: Install openssh client.
        run: sudo apt install -y openssh-client
      - name: Add private key to runner.
        run: mkdir -p ~/.ssh
      - name: Add private ssh key to runner.
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo '"$SSH_KEY"' >> ~/.ssh/approved_keys
      - shell: bash
        env:
          PROD_USER: ${{ secrets.PRODUCTION_USER }}
          PROD_SERVER: ${{ secrets.PRODUCTION_SERVER }}
          SSH_CONNECT_STR: $PROD_USER@$PROD_SERVER
        run: |
          echo $SSH_CONNECT_STR
      - run: ls -la
