name: Update Production Site        # name of workflow
on:                                 # event on which to execute the workflow
  push:                             # when to execute actions
    branches:                       # listen for on these branch(es)
      - master                  
jobs:                               # jobs to execute on event
  git-pull-on-prod:                 
    name: Git Pull on Production
    runs-on: ubuntu-latest          # the type of runner this will execute on
    steps:
      - name: Execute git commands over ssh using private key.
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.PRODUCTION_SERVER }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/anthony/public_html/ci-cd-example/prod   # pwd of directory
            git pull                                          # pull updates from git